g++ -o main main.cpp interpreter.cpp Basicop.cpp Attribute.cpp
# main: main.o interpreter.o                             
#     g++ -o main main.o interpreter.o
# main.o: main.cpp
#     g++ -c main.cpp
# interpreter.o: interpreter.cpp
#     g++ -c interpreter.cpp

# clean:
#      rm *.o
#      rm main

g++ -o main main.cpp Basicop.cpp Attribute.cpp Interpreter.cpp SqlError.cpp -std=c++11